###
# Configuration for Nginx web server
#
# The conditionals need to be cleaned up. This is kind of a hack job
# when I split the deployment so you didn't have to use SSL.
---

#- name: check if nginx ssl directory exists
 # stat: path=/etc/nginx/{{app_name}}
 # register: ssldir

#- name: create ssl directory for nginx if it does not already exist
 # command: mkdir /etc/nginx/{{app_name}}
 #sudo: yes
 # when: deploy_ssl and ssldir.stat.isdir is not defined

#- name: write SSL certificate
  #template: src=ssl_cert/{{app_name}}.sslchain.crt dest=/etc/nginx/{{app_name}}/{{app_name}}.sslchain.crt
  #sudo: yes
  #when: deploy_ssl
  
#- name: write SSL nginx configuration
 # template: src=nginx_ssl.conf.j2 dest=/etc/nginx/conf.d/{{app_name}}.conf
 # sudo: yes
 # when: deploy_ssl
- name: Deploy .bashrc
  template: src=bashrc.j2 dest=/home/ubuntu/.bashrc
  sudo: yes
  sudo: root

- name: write non-SSL nginx configuration
  template: src=nginx_no_ssl.conf.j2 dest=/etc/nginx/sites-enabled/haptik.conf
  sudo: yes
  sudo_user: root
  when: not deploy_ssl

- name: check if nginx has default symbolic linked website file
  stat: path=/etc/nginx/sites-enabled/default
  register: nginx_default_file

- name: delete default symbolic linked website on nginx
  command: rm /etc/nginx/sites-enabled/default
  sudo: yes
  sudo_user: root
  when: nginx_default_file.stat.exists
  notify:
    - restart nginx

