###
# updates the APT package cache and install packages necessary for web
# servers
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes 
  sudo: yes
  sudo_user: root

- name: ensure web server packages/build tools are installed
  apt: name={{item}}
  sudo: yes
  sudo_user: root
  with_items:
    - git
    - python-dev
    - libpq-dev
    - python-virtualenv
    - nginx
    - supervisor
    - build-essential
    - libssl-dev 
    - libffi-dev 
    - python-dev
    - libmysqlclient-dev 
    - nodejs
